// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMxdU7CASx0mmslRhLG0wbjo0vQmPq0aU',
    appId: '1:80179687611:web:e08d1fcd38aa91cb16b99e',
    messagingSenderId: '80179687611',
    projectId: 'roadcycle-d8d06',
    authDomain: 'roadcycle-d8d06.firebaseapp.com',
    storageBucket: 'roadcycle-d8d06.appspot.com',
    measurementId: 'G-5N6Q7P5VCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJY8BjUi3hjsqNs5JPmyZaw-Top35evvA',
    appId: '1:80179687611:android:57e17006a620be4316b99e',
    messagingSenderId: '80179687611',
    projectId: 'roadcycle-d8d06',
    storageBucket: 'roadcycle-d8d06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfLnALUdqtj9weZpWm7bZL3ij9ZcgV3RI',
    appId: '1:80179687611:ios:37e75585770f06df16b99e',
    messagingSenderId: '80179687611',
    projectId: 'roadcycle-d8d06',
    storageBucket: 'roadcycle-d8d06.appspot.com',
    iosClientId:
        '80179687611-2v4bmq6a53oeiofes18qldr06mljie32.apps.googleusercontent.com',
    iosBundleId: 'gr1.roadcycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfLnALUdqtj9weZpWm7bZL3ij9ZcgV3RI',
    appId: '1:80179687611:ios:37e75585770f06df16b99e',
    messagingSenderId: '80179687611',
    projectId: 'roadcycle-d8d06',
    storageBucket: 'roadcycle-d8d06.appspot.com',
    iosClientId:
        '80179687611-2v4bmq6a53oeiofes18qldr06mljie32.apps.googleusercontent.com',
    iosBundleId: 'gr1.roadcycle',
  );
}
